language: python
services:
  - docker
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - pytest
  - docker build -t cschreep/hello-world -f Dockerfile .
  - docker push cschreep/hello-world